use ds4_core::{
    resolve_plan, serving_caps, shape_for_variant, EngineFacts, ServingRequest, SpecLane, Variant,
    VERIFIED_PREFILL_CHUNKS,
};
use std::fmt::Write as _;

// Only catalog membership is listed here. Every capability and bound comes
// from the same policy used by admission and ds4-perf serving-controls.
const VARIANTS: [Variant; 15] = [
    Variant::Flash,
    Variant::Pro,
    Variant::SolarOpen2_250B,
    Variant::Motif3,
    Variant::Kexaone236B,
    Variant::Dots3NotePrev,
    Variant::Qwen38FlashNext,
    Variant::Glm53Flash,
    Variant::K2Horizon375B,
    Variant::InklingSmall,
    Variant::Step37Flash,
    Variant::Ling30FlashVl,
    Variant::Mimo26Flash,
    Variant::NaiveN05Flash,
    Variant::IQuestQ1,
];

fn bound(value: Option<u32>) -> String {
    value.map_or_else(|| "—".into(), |n| n.to_string())
}

pub fn render() -> String {
    let mut out = String::from(
        "# Serving capabilities\n\n\
<!-- Generated by crates/ds4-core/examples/serving_docs.rs. Do not edit. -->\n\n\
This table is generated from `ds4_core::serving_caps` and the resolved\n\
plan's `controls`, which also supply `ds4-perf serving-controls`.\n\
`qualified` describes the recorded artifact and workload scope, not every\n\
quantization, context, concurrency, media input or feature combination.\n\
`unverified` means implemented (`Support::Present`); `none` means unsupported.\n\
Consult the [release ledger](releases/v0.1.3.md) and\n\
[family contracts](ds4-dfm-model-families.md) for evidence and limits.\n\n\
## Execution\n\n\
Cells show the available lane or mode and its qualification. An opt-in\n\
capability still requires explicit selection and successful native fitting.\n\
The request's effective and qualified plan remains authoritative.\n\n\
| Model | Banks | Prefix reuse | Disk KV | Snapshot | MTP kind / lane / support |\n\
|---|---|---|---|---|---|\n",
    );
    let rows: Vec<_> = VARIANTS
        .into_iter()
        .map(|variant| {
            let shape = shape_for_variant(variant);
            let caps = serving_caps(shape.family, variant);
            let mut request = ServingRequest::default();
            if let Some(cap) = caps.ctx_max {
                request.ctx = request.ctx.min(cap as i32);
            }
            let plan = resolve_plan(&request, Some(caps), &EngineFacts::default());
            (shape.name, caps, plan.to_json())
        })
        .collect();
    for (name, caps, plan) in &rows {
        let controls = &plan["controls"];
        let kind = format!("{:?}", caps.mtp);
        let lane = match caps.spec_lane {
            SpecLane::None => "none",
            SpecLane::Serial => "serial",
            SpecLane::Bank => "bank",
            SpecLane::Both => "serial + bank",
        };
        writeln!(
            out,
            "| {name} | {} / {} | {} / {} | {} | {} | {kind} / {lane} / {} |",
            controls["banks"].as_str().expect("known bank mode"),
            caps.bank_support.as_str(),
            controls["prefix_reuse"].as_str().expect("known reuse mode"),
            caps.reuse_support.as_str(),
            controls["disk"].as_str().expect("known disk support"),
            caps.snapshot.as_str(),
            controls["mtp"].as_str().expect("known MTP support")
        )
        .unwrap();
    }
    out.push_str("\n## Bounds and allocator controls\n\n\
The runtime context cap is an admission bound, not a qualification claim.\n\
`—` means the capability table declares no bound or recorded value; it does\n\
not mean unlimited capacity. Qualified columns retain their workload scope.\n\n\
| Model | Runtime context cap | Qualified context | Qualified banks | Qualified prompt | Native prefill environment |\n\
|---|---:|---:|---:|---:|---|\n");
    for (name, caps, plan) in &rows {
        let env = plan["controls"]["native_prefill_env"]
            .as_str()
            .map_or_else(|| "—".into(), |s| format!("`{s}`"));
        writeln!(
            out,
            "| {name} | {} | {} | {} | {} | {env} |",
            bound(caps.ctx_max),
            bound(caps.qualified_ctx),
            bound(caps.qualified_banks),
            bound(caps.qualified_prompt)
        )
        .unwrap();
    }
    let chunks = VERIFIED_PREFILL_CHUNKS.map(|n| n.to_string()).join(", ");
    writeln!(
        out,
        "\nScheduler chunk candidates: {chunks}. The resolved plan only offers\n\
values at or below its known native capacity. Unknown capacity offers no\n\
candidate. These are scheduler controls, not measurements or speed claims."
    )
    .unwrap();
    out.push_str("\n## Qualification notes\n\n");
    for (name, _, plan) in &rows {
        let note = plan["qualified"]["note"]
            .as_str()
            .expect("qualification note");
        if note.is_empty() {
            continue;
        }
        writeln!(out, "- **{name}:** {}.", note.trim_end_matches('.')).unwrap();
    }
    out.push_str(
        "\nRegenerate without loading a model:\n\n\
```sh\n\
cargo run -q -p ds4-core --example serving_docs > docs/serving-capabilities.md\n\
cargo test -p ds4-core --test serving_docs\n\
```\n",
    );
    out
}
